### ISSUE TITLE
Publickkey error

### ISSUE THREAD

**Issue by monaw** [zhangyuanxun/cipres#4]
After submitting a job, following error shows up in the submitJob.log:

```
[...]
Jan 16 2019 12:28:43 [read-1] DEBUG -         SSLConnectionPool:281   [task=7, job=NGBW-JOB-MATLAB_TG-70C0943106C7438E9D6E8B796AC8421E] | Connect to lewis.rnet.missouri.edu with yzhang, /home/cipresuser/.ssh/id_rsa, null
Jan 16 2019 12:28:46 [read-1] ERROR -         SSLConnectionPool:310   [task=7, job=NGBW-JOB-MATLAB_TG-70C0943106C7438E9D6E8B796AC8421E] | Error connecting to yzhang@lewis.rnet.missouri.edu.
java.io.IOException: Publickey authentication failed.
	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:314)
	at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:466)
	at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:519)
[...]

```

**Comment by monaw** [comment]
@zhangyuanxun - I noticed that in /home/cipresuser/.ssh/ there is id_rsa but not id_rsa.pub  Do you know why?  Can I recreate the public and private keys?

**Comment by zhangyuanxun** [comment]
Hi Mona,

Currently, Lewis is down because of maintenance. So, we can’t submit job to Lewis.  But the error code is a little confused. 

If you directly login the lewis, there are still some error about authorization. 

mu-020173:~ yuanxunzhang$ ssh -A yzhang@lewis.rnet.missouri.edu
LDAP authorisation check failed
Connection closed by 128.206.234.6 port 22

**Comment by monaw** [comment]
ah ok, perhaps it has to with lewis being down...guess we'll just have to wait...

the error is slightly different using the cipresuser account which is what the gateway will use:

```
(cipres) [js-16-101] cipresuser ~/.ssh-->ssh -A yzhang@lewis.rnet.missouri.edu
LDAP authorisation check failed
Authentication failed.
(cipres) [js-16-101] cipresuser ~/.ssh-->ssh yzhang@lewis.rnet.missouri.edu
LDAP authorisation check failed
Authentication failed.
```

**Comment by monaw** [comment]
system moved from Jetstream VM to Lewis VM
